type: task

# Keep instance warm for 5 minutes after task completion
# This allows consecutive runs to reuse the same instance
idle_duration: 5m

# Reuse existing instances when possible
creation_policy: reuse-or-create

# Use spot instances for cost savings
spot_policy: auto

resources:
  gpu:
    name: MI300X
    count: 1
  cpu: 2..
  memory: 8GB..
  disk: 100GB..

# Backend configuration
backends:
  - hotaisle

# ROCm-ready base image
image: rocm/pytorch:latest

# Environment variables for task execution
env:
  - ROCM_PATH=/opt/rocm
  - HIP_PLATFORM=amd

# Upload the HIP source file
files:
  - ./matmul.hip

# Commands will be injected by dstack_runner.py
# Default example commands for reference:
commands:
  - echo "=== ROCm Environment ==="
  - rocm-smi --showproductname || echo 'rocm-smi not available'
  - hipcc --version || echo 'hipcc not available'
  - echo ""
  - echo "=== Compiling HIP Kernel ==="
  - hipcc matmul.hip -o matmul -O3 || exit 1
  - echo "Compilation successful"
  - echo ""
  - echo "=== Running Kernel ==="
  - ./matmul 1024
  - echo ""
  - echo "=== Execution Complete ==="
