type: task

# Terminate instance immediately after task completion (serverless)
idle_duration: 0s

# Use spot instances for cost savings
spot_policy: auto

resources:
  # GPU configuration - supports MI210, MI250X, MI300A, MI300X
  # This will be overridden by the API call based on user selection
  gpu:
    name: MI300X
    count: 1

# ROCm-ready base image
image: rocm/pytorch:latest

# Environment variables for task execution
env:
  - ROCM_PATH=/opt/rocm
  - HIP_PLATFORM=amd

# No files needed - code will be injected via commands
# files:
#   - ./matmul.hip

# Commands will be injected by dstack_runner.py
# Default example commands for reference:
commands:
  - echo "=== ROCm Environment ==="
  - rocm-smi --showproductname || echo 'rocm-smi not available'
  - hipcc --version || echo 'hipcc not available'
  - echo ""
  - echo "=== Compiling HIP Kernel ==="
  - hipcc solution.hip -o solution -O3 || exit 1
  - echo "Compilation successful"
  - echo ""
  - echo "=== Running Kernel ==="
  - ./solution 1024
  - echo ""
  - echo "=== Execution Complete ==="
