[project]
name = "tensara-engine"
version = "0.1.0"
description = "CUDA runner engine using modal for Tensara"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.11",
    "modal>=0.73.85",
]

[tool.ruff]
line-length = 100